const colors = {
  light: {
    text: "#1a0f0a",
    tint: "#FF6B2B",
    background: "#fdf6f0",
    foreground: "#1a0f0a",
    card: "#ffffff",
    cardForeground: "#1a0f0a",
    primary: "#FF6B2B",
    primaryForeground: "#ffffff",
    secondary: "#fde8d8",
    secondaryForeground: "#1a0f0a",
    muted: "#f5e6d8",
    mutedForeground: "#8a6040",
    accent: "#FF6B2B",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e8d5c4",
    input: "#e8d5c4",
  },
  dark: {
    text: "#F5E6D3",
    tint: "#7C8C5E",
    background: "#2C2C28",
    foreground: "#F5E6D3",
    card: "#363632",
    cardForeground: "#F5E6D3",
    primary: "#7C8C5E",
    primaryForeground: "#F0F2EC",
    secondary: "#3C3C38",
    secondaryForeground: "#F5E6D3",
    muted: "#3C3C38",
    mutedForeground: "#9A9A88",
    accent: "#7C8C5E",
    accentForeground: "#F0F2EC",
    destructive: "#ef4444",
    destructiveForeground: "#F5E6D3",
    border: "#48483E",
    input: "#48483E",
  },
  radius: 14,
};

export default colors;
