const colors = {
  light: {
    text: "#1a0f0a",
    tint: "#FF6B2B",
    background: "#fdf6f0",
    foreground: "#1a0f0a",
    card: "#ffffff",
    cardForeground: "#1a0f0a",
    primary: "#FF6B2B",
    primaryForeground: "#ffffff",
    secondary: "#fde8d8",
    secondaryForeground: "#1a0f0a",
    muted: "#f5e6d8",
    mutedForeground: "#8a6040",
    accent: "#FF6B2B",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e8d5c4",
    input: "#e8d5c4",
  },
  dark: {
    text: "#F5E6D3",
    tint: "#FF6B2B",
    background: "#130E0C",
    foreground: "#F5E6D3",
    card: "#1E1410",
    cardForeground: "#F5E6D3",
    primary: "#FF6B2B",
    primaryForeground: "#130E0C",
    secondary: "#2A1F1A",
    secondaryForeground: "#F5E6D3",
    muted: "#2A1F1A",
    mutedForeground: "#7A5C4E",
    accent: "#FF6B2B",
    accentForeground: "#130E0C",
    destructive: "#ef4444",
    destructiveForeground: "#F5E6D3",
    border: "#3D2B22",
    input: "#3D2B22",
  },
  radius: 14,
};

export default colors;
